CREATE TABLE user (
  Id INTEGER PRIMARY KEY,
  Username VARCHAR NOT NULL,
  Password VARCHAR NOT NULL,
  Karma INTEGER
);
 
CREATE TABLE story (    
    Id INTEGER PRIMARY KEY,
    title VARCHAR NOT NULL,
    Description VARCHAR NOT NULL,
    Date DATETIME NOT NULL,
    Karma INTEGER
);

CREATE TABLE comment (    
    Id INTEGER PRIMARY KEY,
    Description VARCHAR NOT NULL,
    Date DATETIME NOT NULL,
    Karma INTEGER
);

CREATE TABLE channel (    
    Id INTEGER PRIMARY KEY,
    Name VARCHAR NOT NULL,
    Subscriptions INTEGER
);

CREATE TABLE VoteStory (    
    Id_user INTEGER REFERENCES user(Id) PRIMARY KEY,
    Id_story INTEGER REFERENCES story(Id)PRIMARY KEY,
    UpDown INTEGER,
    Date DATETIME NOT NULL
);

CREATE TABLE VoteComment (    
    Id_user INTEGER REFERENCES user(Id) PRIMARY KEY,
    Id_story INTEGER REFERENCES story(Id)PRIMARY KEY,
    UpDown INTEGER,
    Date DATETIME NOT NULL
);

